databases:
  - name: a1-corporation
    plan: free
    databaseName: a1_corporation
    user: a1_corporation_user

services:
  - type: web
    plan: free
    name: mysite
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn JobInsight.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: a1-corporation
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
